@startuml
partition def_diceRoll(): {
    start
    :diceFaces = range(1,7);
    :return random.choice(diceFaces);
    end
} 

partition def_gambleResule(pMoney_gMoney_gChoice_fDice_sDice_thDice): {
    start
    :dicesPoint = firstDice+secondDice+thirdDice;
    if (dicesPoint > 11:) then (yes)
        :print(f"ลูกเต๋าออกมาเป็น {fDice}-{sDice}-{thDice}. รวมเป็น {dicesPoint}");
        :print("ออก สูง***");
        if (gChoice == 'H':) then (yes)
            :print("นาย ชนะ!!!");
            :pMoney += int(gMoney);
            :return pMoney;
        else
            :print("นาย แพ้!!!");
            :pMoney -= int(gMoney);
            :return pMoney;  
        endif
    elseif (dicesPoint < 11:) then (yes)
        :print(f"ลูกเต๋าออกมาเป็น {fDice}-{sDice}-{thDice}. รวมเป็น {dicesPoint}");
        :print("ออก ต่ำ***");
        if (gChoice == 'L':) then (yes)
            :print("นาย ชนะ!!!");
            :pMoney += int(gMoney);
            :return pMoney;
        else
            :print("นาย แพ้!!!");
            :pMoney -= int(gMoney);
            :return pMoney;  
        endif
    else
        :print("ออก ไฮโล 11 แต้ม เจ้ามือกินเรียบ นายแพ้***!!!");
        :pMoney -= int(gMoney);
        :return pMoney;
    endif
    end
}
@enduml